### ISSUE TITLE
Leading space on install code snippets

### ISSUE THREAD

**Issue by mattmazzola** [clerkinc/clerk-docs#133]
https://github.com/clerkinc/clerk-docs/blob/4f22977468ad40c2c6d54087d654c94db2f6c4a8/src/pages/quickstarts/full-stack/remix.mdx#L20C1-L20C3

It seems the indentation / formatting within the component is including the whitespace which is awkward for copy pasting code snippets.

Example (Ignore ending triple backticks rendering)
Current
```
  ```bash filename="your-project" copy
  npm install @clerk/remix
  `` `
```

Remove leading spaces
```
```bash filename="your-project" copy
npm install @clerk/remix
`` `
```

**Comment by perkinsjr** [comment]
Hey Matt,

Appreciate all the PR's and opening this issue. We will take care of this before the docs are ready for public consumption.

Thanks again! 

James
