### ISSUE TITLE
Minor code issues in Remix Quickstart

### ISSUE THREAD

**Issue by mattmazzola** [clerkinc/clerk-docs#146]
There are a few minor repetitions and typos in the Remix quickstart

The import of ClerkApp is repeated in multiple sections

## Introduction of ClerkApp

https://github.com/clerkinc/clerk-docs/blob/df776415a4bd4e8ca9da2a0567584b6e7f18f94f/src/pages/quickstarts/full-stack/remix.mdx#L106-L120

## Addition of ClerkCatchBoundary 

https://github.com/clerkinc/clerk-docs/blob/df776415a4bd4e8ca9da2a0567584b6e7f18f94f/src/pages/quickstarts/full-stack/remix.mdx#L160-L173

I think all the Clerk imports should be consolidated and shown on lines near each other

## Typo for error boundary

This quick start shows the V2_ErrorBoundary and has a typo, although I don't see this in the source code 🤔
The source also doesn't seem to be showing V2_ErrorBoundary so many I am looking in the wrong location

Note: "add n Error Boundary" should be "add **an** Error Boundary"

![image](https://github.com/clerkinc/clerk-docs/assets/2856501/baf9788b-346c-4573-bda5-7776674567ab)

https://github.com/clerkinc/clerk-docs/edit/main/src/pages/quickstarts/full-stack/remix.mdx

**Comment by alexisintech** [comment]
These imports and the typo have been solved ✅😸
