### ISSUE TITLE
Call out our Components' style inheritance in the next.js quickstart guide

### ISSUE THREAD

**Issue by martzoukos** [clerkinc/clerk-docs#17]
By following the two next.js guides in the new Docs ([Next.js Stable](https://beta-docs.clerk.com/quickstarts/next/next) and [Next.js App Router (beta)](https://beta-docs.clerk.com/quickstarts/next/next-beta)), a first-time user will notice that our components don't render as advertised:
![image](https://user-images.githubusercontent.com/329419/225630375-bb9baabc-4a2b-4a5e-a64d-87e40d28417d.png)

This is an expected behavior as our components inherit styles from the surrounding elements, making it easier for the developers to adapt them with little to no style overrides and since next.js stopped loading the Inter font globally in their latest versions, the text appears with the default system fonts.

However, because this is the first time these users might see our components in action, they might be confused for a second and believe that either the installation was not complete or, even worse, that we are doing something wrong.
It might be worth calling out our components behavior in the quickstart guide in order to reassure them.

**Comment by perkinsjr** [comment]
Completed today with a callout in the guides.

**Comment by martzoukos** [comment]
I saw that. Thank you very much James!
