### ISSUE TITLE
Feedback for “<OrganizationSwitcher />”

### ISSUE THREAD

**Issue by Yashpreetrana4790** [clerkinc/clerk-docs#173]
import { OrganizationSwitcher } from "@clerk/nextjs";

const Topbar = () => {
  
  return (
  
        <OrganizationSwitcher
          appearance={{
            elements: {
              organizationSwitcherTrigger: "py-2 px-4"
            }
          }}
        />
  );
};

export default Topbar;
so this is the code I am using but it is actually not showing anything

**Comment by royanger** [comment]
@Yashpreetrana4790, I just dropped your code into my test app and it worked fine. Please contact us on our [discord](https://discord.gg/vVQHBXkSEY) or [email support](https://clerk.com) (click the help/chat icon in the bottom right) and we can troubleshoot this. At this repo is for docs, I'm going to close this.

**Comment by Yashpreetrana4790** [comment]
> @Yashpreetrana4790, I just dropped your code into my test app and it worked fine. Please contact us on our [discord](https://discord.gg/vVQHBXkSEY) or [email support](https://clerk.com) (click the help/chat icon in the bottom right) and we can troubleshoot this. At this repo is for docs, I'm going to close this.

Thanks I had managed to work with it
