### ISSUE TITLE
Broken link: https://clerk.com/docs/integration/webhooks

### ISSUE THREAD

**Issue by bkyerv** [clerkinc/clerk-docs#229]
Link to the webhook docs that is published on this page is broken: https://dashboard.clerk.com/apps/app_2UOOoD9SdBm046btfsIJztYGqXi/instances/ins_2UOOoBnO0WCStraHVHC5Wr6OVsb/webhooks

page at the above link works, but the link published on that page is broken

**Comment by Shivam0887** [comment]
They made a slight change in the URL. In the URL, change 'integration' to 'integrations', that's all.
New URL: [https://clerk.com/docs/integrations/webhooks](url)

**Comment by alexisintech** [comment]
Thank you for this find :)
Solved with https://github.com/clerkinc/clerk-marketing/pull/748
