### ISSUE TITLE
Feedback for “Use Clerk with Next.js”

### ISSUE THREAD

**Issue by drewkennelly** [clerkinc/clerk-docs#24]
I have followed each step exactly from https://beta-docs.clerk.com/quickstarts/nextjs/app-router and am getting the following error:

**Error: Invariant: Method expects to have requestAsyncStorage, none available**

Packages
Next.js: 13.2.4
@clerk/nextjs: ^4.11.13

<img width="966" alt="Screenshot 2023-03-24 at 1 12 50 PM" src="https://user-images.githubusercontent.com/279851/227391599-0d980bdf-249a-488d-acca-49d64a545558.png">

**Comment by perkinsjr** [comment]
Please reach out to support this is not a documentation issue.
