### ISSUE TITLE
Migration of Clerk Doc Pages from Sanity CMS to MDX

### ISSUE THREAD

**Issue by yiremorlans** [clerkinc/clerk-docs#243]
## Summary
I would like to help in migrating two following clerk doc pages from Sanity CMS to MDX:
- [Deleting users page](https://clerk.com/docs/users/deleting-users) under Users
- [Web3 authentication](https://clerk.com/docs/users/web3-wallets) under Users/Guides

## Acceptance criteria
- [ ] Ensure all the content and links are the same and functional
- [ ] Use proper MDX components and headers for content and headings

**Comment by alexisintech** [comment]
Discussed with contributor privately - these pages are being worked on internally. Gave this contributor other options/ideas for contributions!
