### ISSUE TITLE
Email & SMS templates Page from Sanity CMS to MDX 

### ISSUE THREAD

**Issue by HondaChan14** [clerkinc/clerk-docs#247]
# Summary
I would like to contribute in migrating following clerk doc page from Sanity CMS to MDX:

[Email & SMS templates](https://clerk.com/docs/authentication/configuration/email-options) under Configuration

## Acceptance criteria
- [ ] Ensure all the content and links are the same and functional
- [ ] Use proper MDX components

**Comment by alexisintech** [comment]
Hey @HondaChan14 
We would love to have you contribute!
This page is currently being worked on, on [this branch](https://github.com/clerkinc/clerk-docs/tree/aa/email-options)

If you would like, I'd recommend trying out any of these pages:
https://clerk.com/docs/backend-requests/handling/nodejs
https://clerk.com/docs/backend-requests/handling/go
https://clerk.com/docs/backend-requests/handling/gatsby
https://clerk.com/docs/backend-requests/handling/ruby-rails

**Comment by HondaChan14** [comment]
> 

Thank you so much I wuld def love to contribute to Nodejs and Gatsby. Ill submit a new issue
