### ISSUE TITLE
Migration of metadata page from Sanity CMS to MDX

### ISSUE THREAD

**Issue by yiremorlans** [clerkinc/clerk-docs#253]
## Summary
I would like to help migrate the following clerk doc page from Sanity CMS to MDX: [Metadata](https://clerk.com/docs/organizations/metadata)

## Acceptance criteria
- [ ] Ensure all the content and links are the same and functional
- [ ] Use proper MDX components, themes, and headers for content, and headings

## Notes
Discussed with @alexisintech working on the above page

**Comment by alexisintech** [comment]
Approved to be worked on 😸✅
