### ISSUE TITLE
Feedback for “getAuth()”

### ISSUE THREAD

**Issue by nguyenbry** [clerkinc/clerk-docs#27]
In the `Usage with getToken` section, the `data` variable is undefined. 
<img width="533" alt="image" src="https://user-images.githubusercontent.com/106679547/227813713-4e210db2-88c7-4d3a-9a59-3db1d220d604.png">

**Comment by perkinsjr** [comment]
Thanks for the feedback there is an assumption here that you are retrieving some data and returning it, I will shore this up in the future.
