### ISSUE TITLE
Is primaryEmailAddress still a thing

### ISSUE THREAD

**Issue by spookyuser** [clerkinc/clerk-docs#275]
I can't seem to access it on the user object only `primaryEmailAddressId`

**Comment by alexisintech** [comment]
Hi! So, I actually just learned this recently, and it depends on how you are trying to access the `User` object. If it is from the frontend API, then `primaryEmailAddress` should be accessible. If it is from the backend API, you can do something like this:

```tsx
import type { NextApiRequest, NextApiResponse } from "next";
import { getAuth } from "@clerk/nextjs/server";
import { clerkClient } from "@clerk/nextjs";
 
export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  try {
    const { userId } = getAuth(req);
 
    if (!userId) {
      return res.status(401).json({ error: "Unauthorized" });
    }
 
    const user = userId ? await clerkClient.users.getUser(userId) : null;
 
    // Retrieve the user's web3Wallet
    const primaryEmailId = user ? user.primaryEmailAddressId : null;
    const primaryEmail = user
      ? user.primaryEmailAddresses.find((email) => email.id === primaryEmailId)
      : null;
 
    res.status(200).json({ email: email });
  } catch (e) {
    console.log(e);
 
    res.status(500).json({
      error: "Something went wrong retrieving the email address from Clerk",
    });
  }
}
```

Also, `primaryEmailAddress` is also in [Sessions](https://dashboard.clerk.com/last-active?path=sessions) as a shortcode.

**Comment by spookyuser** [comment]
Oh thanks sm! I think ther should b a note abt this on the this porperty in the docs, bc it doesnt specify the distinction rn https://clerk.com/docs/references/javascript/user/user
