### ISSUE TITLE
Next.js App Router Middleware

### ISSUE THREAD

**Issue by alexanderl19** [clerkinc/clerk-docs#30]
https://beta-docs.clerk.com/quickstarts/nextjs/app-router#add-middleware
"Middleware should be placed at the root of your project."

The middleware file needs to be placed in the `src` folder, if in use. The rest of Clerk's documentation is pretty verbose, so making note of `vercel dev` might be a good idea for new users.

**Comment by perkinsjr** [comment]
Appreciate the feedback here, this is very dependent on the user and what they select during the CLI. If they select `src/` that then becomes the root project folder, however if they select no it goes at the root folder. 

I added a callout to make sure people know where to place it if using the `src/`
