### ISSUE TITLE
Scrollbar isn't restored when closing UserProfile modal

### ISSUE THREAD

**Issue by krumpyzoid** [clerkinc/clerk-docs#40]
Device: MacOS
Browser: Chrome
Package: @clerk/clerk-react

When closing the UserProfile modal, I cannot scroll until I refresh the page. The bug isn't happening on mobile device. It happens when opening the modal through the `<UserButton />` and `openUserProfile()`

**Comment by krumpyzoid** [comment]
To provide more context:
The issue is happening in local environment but it is working properly on the live website

**Comment by perkinsjr** [comment]
This isn’t the correct place for this, this is issues surrounding documentation , please reach out via clerk.com/support
