### ISSUE TITLE
Feedback for “Use Clerk with Next.js”

### ISSUE THREAD

**Issue by davit-b** [clerkinc/clerk-docs#43]
For people using the NextJS `/src` directory convention, they have to add the `middelware.js/ts` file inside the `/src` directory, not inside the root of the project. 

Adding some mention of this in the docs specifically in the [configure-middleware](https://clerk.com/docs/nextjs/configure-middleware)

![Screenshot 2023-04-20 at 6 04 35 PM](https://user-images.githubusercontent.com/12516060/233497211-1f0aefc8-69d0-48f8-84ea-89cc0a0edcf6.png)

Would save onboarding users from a sharp edge (if they are using the `src` directory)

**Comment by perkinsjr** [comment]
Appreciated. Added to the to do board
