### ISSUE TITLE
app is not compiling when following Expo docs

### ISSUE THREAD

**Issue by varand-pez** [clerkinc/clerk-docs#442]
Hi all, I'm trying to use Clerk as my app's user management and facing issues when following [the docs](https://clerk.com/docs/quickstarts/expo).

So when I got to step 3, I tried to run the app to make sure the wirings are correct. The first error I got was missing dependency, `expo-auth-session`. Then I installed it with it's required/peer dependency mentioned in [Expo docs](https://docs.expo.dev/versions/latest/sdk/auth-session/).

Then started the app again and I'm getting this:

![Simulator Screenshot - iPhone 15 Pro Max - 2023-10-19 at 23 02 15](https://github.com/clerkinc/clerk-docs/assets/47469980/4d817ae6-b5c2-4ae9-8606-270b94d003e5)

I'm using "expo": "49.0.15", with [Expo Router](https://docs.expo.dev/routing/introduction/)

Is Clerk not supporting this routing mechanism yet?

Thank you in advance.

**Comment by varand-pez** [comment]
I did some more experiments and tried to import `<ClerkProvider>` from `"@clerk/clerk-react`.
At this time the app throws an error saying the CLERK_PUBLISHABLE_KEY is incorrect, but I have checked it multiple times, and it's correct.

![Simulator Screenshot - iPhone 15 Pro Max - 2023-10-19 at 23 17 43](https://github.com/clerkinc/clerk-docs/assets/47469980/ea77bf5c-d139-44ad-9be5-52351489a99e)

**Comment by SimbaWANGU** [comment]
Hello @varand-pez 

I was stuck on the second issue when using expo until two minutes ago. When following the docs as well, I imported the @clerk/clerk-react package and passing my publishableKey as the docs asked. I changed the import to @cler/clerk-expo and reloaded my app and it worked.

I hope it will work for you as well :)

I'm using expo-router as well.

**Comment by varand-pez** [comment]
hmmm, yes many times, I went back and forth about those imports.
thank you for trying to unblock me, I still have the issue.

**Comment by varand-pez** [comment]
I upgraded to the latest version `"@clerk/clerk-expo": "^0.19.14",` but the issue persist. can anyone from the team help me here.
It's worth to mention that my code is already connected to convex and was working fine before adding the clerk dep.

**Comment by LekoArts** [comment]
Hi, thanks for opening the issue.

If you have found a bug with the Expo SDK, please create a bug report here: https://github.com/clerkinc/javascript
If you need help with Expo, head over to our [Discord server](https://clerk.com/discord).

This repository is about the Clerk documentation and as such I'm closing this issue.

**Comment by varand-pez** [comment]
Thanks @LekoArts I thought it's relevant because I was following the docs. I'll try your provided link then.
